name = "Erdos971"
version = "0.2.0"
defaultTargets = ["Erdos971"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "BombieriVinogradov"
git = "https://github.com/kimihiro64/bombieri-vinogradov.git"
rev = "7a1748306e026825ed6a5555516cc2f28989b2ac"

[[lean_lib]]
name = "Erdos971"
